/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package AnExpertSystem;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.sl.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author MF
 */
public class ClientInformation extends javax.swing.JFrame {
    
    
    
    
   String eyeColorText,bloodGrp;
   String pulseText,temper;
   static DefaultTableModel model = null;
    private Connection con;
    private Statement stm;
    public ClientInformation() {
        initComponents();
         try
		{
			Class.forName("com.mysql.jdbc.Driver");
		        con =(Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/expert_system?zeroDateTimeBehavior=convertToNull","root", "");
                        stm = (Statement) con.createStatement();
		      /// System.out.println(stmt.executeUpdate(sql));
                      //JOptionPane.showMessageDialog(null, "Connected");
		}
		catch(Exception e){
			JOptionPane.showMessageDialog(null, "Not Connected");
		}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        comboBox = new javax.swing.JComboBox<>();
        eyeColor = new javax.swing.JTextField();
        temperature = new javax.swing.JTextField();
        pulse = new javax.swing.JTextField();
        jPanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        headN = new javax.swing.JCheckBox();
        seizN = new javax.swing.JCheckBox();
        weightY = new javax.swing.JCheckBox();
        feelY = new javax.swing.JCheckBox();
        bleedY = new javax.swing.JCheckBox();
        FreqY = new javax.swing.JCheckBox();
        redY = new javax.swing.JCheckBox();
        leftY = new javax.swing.JCheckBox();
        headY = new javax.swing.JCheckBox();
        seizY = new javax.swing.JCheckBox();
        vomN = new javax.swing.JCheckBox();
        weightN = new javax.swing.JCheckBox();
        feelN = new javax.swing.JCheckBox();
        bleedN = new javax.swing.JCheckBox();
        freqN = new javax.swing.JCheckBox();
        redN = new javax.swing.JCheckBox();
        leftN = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        vomY = new javax.swing.JCheckBox();
        symptomsPanel = new javax.swing.JPanel();
        quicklyRad = new javax.swing.JRadioButton();
        slowlyRad = new javax.swing.JRadioButton();
        saveBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Client Information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 12), new java.awt.Color(0, 204, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(102, 255, 51));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Eye Color:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Temperature:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Blood Group:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Pulse: ");

        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "A+(Ve)", "A-(Ve)", "B+(Ve)", "B-(Ve)", "AB+(Ve)", "AB-(Ve)", "O+(Ve)", "O-(Ve)" }));

        eyeColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eyeColorActionPerformed(evt);
            }
        });

        temperature.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temperatureActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eyeColor, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(temperature)
                    .addComponent(pulse, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                .addGap(45, 45, 45))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(eyeColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(temperature, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(comboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pulse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel.setBackground(new java.awt.Color(204, 255, 204));
        jPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Symptoms", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 12), new java.awt.Color(0, 153, 0))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Headaches:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Seizures:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Vomiting:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Weight loss or loss appetite:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Feeling weak or tried:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("Bleeding and bruisiing: ");

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Frequent infection:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel17.setText("Red or purple spot in the skin:");

        buttonGroup2.add(headN);
        headN.setText("NO");
        headN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                headNActionPerformed(evt);
            }
        });

        buttonGroup3.add(seizN);
        seizN.setText("NO");
        seizN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seizNActionPerformed(evt);
            }
        });

        buttonGroup5.add(weightY);
        weightY.setText("YES");
        weightY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightYActionPerformed(evt);
            }
        });

        buttonGroup6.add(feelY);
        feelY.setText("YES");
        feelY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                feelYActionPerformed(evt);
            }
        });

        buttonGroup7.add(bleedY);
        bleedY.setText("YES");
        bleedY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bleedYActionPerformed(evt);
            }
        });

        buttonGroup8.add(FreqY);
        FreqY.setText("YES");

        buttonGroup9.add(redY);
        redY.setText("YES");

        buttonGroup10.add(leftY);
        leftY.setText("YES");

        buttonGroup2.add(headY);
        headY.setText("YES");
        headY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                headYActionPerformed(evt);
            }
        });

        buttonGroup3.add(seizY);
        seizY.setText("YES");

        buttonGroup4.add(vomN);
        vomN.setText("NO");

        buttonGroup5.add(weightN);
        weightN.setText("NO");

        buttonGroup6.add(feelN);
        feelN.setText("NO");

        buttonGroup7.add(bleedN);
        bleedN.setText("NO");
        bleedN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bleedNActionPerformed(evt);
            }
        });

        buttonGroup8.add(freqN);
        freqN.setText("NO");

        buttonGroup9.add(redN);
        redN.setText("NO");

        buttonGroup10.add(leftN);
        leftN.setText("NO");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel18.setText("Left untreated");

        buttonGroup4.add(vomY);
        vomY.setText("YES");

        symptomsPanel.setBackground(new java.awt.Color(153, 153, 153));
        symptomsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Symptoms are", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 153, 0))); // NOI18N

        buttonGroup1.add(quicklyRad);
        quicklyRad.setText("Quickly Develop");

        buttonGroup1.add(slowlyRad);
        slowlyRad.setText("Slowly Develop");
        slowlyRad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slowlyRadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout symptomsPanelLayout = new javax.swing.GroupLayout(symptomsPanel);
        symptomsPanel.setLayout(symptomsPanelLayout);
        symptomsPanelLayout.setHorizontalGroup(
            symptomsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(symptomsPanelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(quicklyRad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(slowlyRad)
                .addGap(20, 20, 20))
        );
        symptomsPanelLayout.setVerticalGroup(
            symptomsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(symptomsPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(symptomsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quicklyRad)
                    .addComponent(slowlyRad))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        saveBtn.setBackground(new java.awt.Color(51, 255, 51));
        saveBtn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel18))
                                .addGap(51, 51, 51)
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(headY)
                                            .addComponent(seizY)
                                            .addComponent(vomY)))
                                    .addGroup(jPanelLayout.createSequentialGroup()
                                        .addGap(23, 23, 23)
                                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(leftY)
                                            .addComponent(redY)
                                            .addComponent(FreqY)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(feelY)
                                            .addComponent(weightY)
                                            .addComponent(bleedY))
                                        .addGap(2, 2, 2))))
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bleedN)
                            .addComponent(vomN)
                            .addComponent(weightN)
                            .addComponent(feelN)
                            .addComponent(freqN)
                            .addComponent(redN)
                            .addComponent(leftN)
                            .addComponent(headN)
                            .addComponent(seizN))
                        .addContainerGap(95, Short.MAX_VALUE))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(symptomsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveBtn)
                .addGap(214, 214, 214))
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(headY)
                    .addComponent(headN))
                .addGap(17, 17, 17)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(seizY)
                    .addComponent(seizN))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(vomY)
                        .addComponent(vomN))
                    .addComponent(jLabel8))
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(weightY)
                            .addComponent(weightN)))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel9)
                        .addGap(28, 28, 28)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(feelY)
                            .addComponent(feelN))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelLayout.createSequentialGroup()
                                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(bleedY)
                                    .addComponent(bleedN))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(FreqY)
                                .addComponent(freqN)))))
                .addGap(12, 12, 12)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(redY)
                        .addComponent(redN))
                    .addGroup(jPanelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel17)))
                .addGap(18, 18, 18)
                .addGroup(jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftY)
                    .addComponent(leftN)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addComponent(symptomsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(saveBtn)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eyeColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eyeColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eyeColorActionPerformed

    private void temperatureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temperatureActionPerformed
        
    }//GEN-LAST:event_temperatureActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
      getSymptoms();
       eyeColorText= eyeColor.getText();
       bloodGrp=comboBox.getSelectedItem().toString();
       temper=temperature.getText();
       pulseText=pulse.getText();
       if(eyeColorText.equals("")){
        JOptionPane.showMessageDialog(null, "please enter the Name");
        }else if(bloodGrp.equals("")){
          JOptionPane.showMessageDialog(null, "please enter the Parent Name");   
        }else if(temper.equals("")){
          JOptionPane.showMessageDialog(null, "please enter the Patient Id");   
        }else if(pulseText.equals("")){
          JOptionPane.showMessageDialog(null, "please enter the Contact number");   
        }
       
        try {    
        //Sql Query 
               
        String sql="INSERT INTO client_information(eye_color,temperature,blood_group,pulse)"+
                      "VALUES('"+eyeColorText+"','"+Integer.valueOf(temper)+"','"+bloodGrp+"','"+Integer.valueOf(pulseText)+"');";
                stm.executeUpdate(sql);
                //JOptionPane.showMessageDialog(null, "data saved");   
            } catch (SQLException ex) {
                Logger.getLogger(ClientInformation.class.getName()).log(Level.SEVERE, null, ex);
                        //JOptionPane.showMessageDialog(null, "please Fill in the Text  Field");

            }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void bleedNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bleedNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bleedNActionPerformed

    private void headYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_headYActionPerformed

    private void bleedYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bleedYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bleedYActionPerformed

    private void feelYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_feelYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_feelYActionPerformed

    private void weightYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightYActionPerformed

    private void seizNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seizNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seizNActionPerformed

    private void headNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_headNActionPerformed

    private void slowlyRadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slowlyRadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_slowlyRadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientInformation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox FreqY;
    private javax.swing.JCheckBox bleedN;
    private javax.swing.JCheckBox bleedY;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JTextField eyeColor;
    private javax.swing.JCheckBox feelN;
    private javax.swing.JCheckBox feelY;
    private javax.swing.JCheckBox freqN;
    private javax.swing.JCheckBox headN;
    private javax.swing.JCheckBox headY;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox leftN;
    private javax.swing.JCheckBox leftY;
    private javax.swing.JTextField pulse;
    private javax.swing.JRadioButton quicklyRad;
    private javax.swing.JCheckBox redN;
    private javax.swing.JCheckBox redY;
    private javax.swing.JButton saveBtn;
    private javax.swing.JCheckBox seizN;
    private javax.swing.JCheckBox seizY;
    private javax.swing.JRadioButton slowlyRad;
    private javax.swing.JPanel symptomsPanel;
    private javax.swing.JTextField temperature;
    private javax.swing.JCheckBox vomN;
    private javax.swing.JCheckBox vomY;
    private javax.swing.JCheckBox weightN;
    private javax.swing.JCheckBox weightY;
    // End of variables declaration//GEN-END:variables
public void getSymptoms(){
String headVal="";
String symtopVal="";
String value1="";
String value3="";
if(headY.isSelected() && seizY.isSelected()
        && vomY.isSelected() && weightY.isSelected() && feelY.isSelected()
        && bleedY.isSelected() && FreqY.isSelected()
        && redY.isSelected() && leftY.isSelected()){
    headVal="Yes";
}else if ( weightY.isSelected() && feelY.isSelected()
        && bleedY.isSelected() && FreqY.isSelected()
        && redY.isSelected() || leftY.isSelected()){
    value1="Yes";
      
}else if(headY.isSelected() && seizY.isSelected() && vomY.isSelected()){
    value3="Yes";
}

if(quicklyRad.isSelected()){
symtopVal="Quickly";
}else if(slowlyRad.isSelected()){
    symtopVal="Slowly";
}


if(headVal.equals("Yes") && symtopVal.equals("Quickly")){
    amlDialogBox();
    
    // JOptionPane.showMessageDialog(null, "");
}else if(headVal.equals("Yes") && symtopVal.equals("Slowly")){
    cmlDialogBox();
  
   // JOptionPane.showMessageDialog(null, "CML= Choronic Myeloid Leukemia");
} else if(value1.equals("Yes") && symtopVal.equals("Quickly")){
    allDialogBox();
     
   // JOptionPane.showMessageDialog(null,"ALL= Acute Lymphocytic Leukemia");
} else if(value1.equals("Yes") && symtopVal.equals("Slowly")){
    cllDialogBox();
    
    
} else if(value3.equals("Yes")){
    noAction();
     //JOptionPane.showMessageDialog(null, "He/She is normal position");
}  else{
    JOptionPane.showMessageDialog(null, "please right information");}
    

}
public void amlDialogBox(){
    

String msg = "<html>Please Test<br>"
        +"<ul>"
        + "<li>Collect blood sample(PBF=peripheral Blood Film Study).</li>"
        + "<li>Bone Marrow Study</li>"
        + "<li>Chest X-RAY</li>"
        + "<li>MRI</li>"
        + "<li>City Scan</li>"
        +"</ul>";
int input = JOptionPane.showOptionDialog(null, msg, "Check Up", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);

if(input == JOptionPane.OK_OPTION)
{
    int amlValue=85;
    ExcelSheet excel = new ExcelSheet(amlValue);
           excel.setVisible(true);
           excel.setTitle("Report");
           this.dispose();
}
}
public void cmlDialogBox(){

String msg ="<html>Please Test<br>"
        +"<ul>"
        + "<li>Collect blood sample(PBF=peripheral Blood Film Study).</li>"
        + "<li>Bone Marrow Study</li>"
        + "<li>Chest X-RAY</li>"
        + "<li>MRI</li>"
        + "<li>City Scan</li>"
        +"</ul>";
int input = JOptionPane.showOptionDialog(null, msg, "Check Up", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);

if(input == JOptionPane.OK_OPTION)
{
    int cmlValue=80;
     ExcelSheet excel = new ExcelSheet(cmlValue);
           excel.setVisible(true);
           excel.setTitle("Report");
           this.dispose();
}
  /*  */
}
public void allDialogBox(){

String msg = "<html>Please Test<br>"
        +"<ul>"
        + "<li>Collect blood sample(PBF=peripheral Blood Film Study).</li>"
        + "<li>Bone Marrow Study</li>"
        + "<li>Chest X-RAY</li>"
        + "<li>MRI</li>"
        + "<li>City Scan</li>"
        +"</ul>";
int input = JOptionPane.showOptionDialog(null, msg, "Check Up", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);

if(input == JOptionPane.OK_OPTION)
{
    int allValue=75;
    ExcelSheet excel = new ExcelSheet(allValue);
           excel.setVisible(true);
           excel.setTitle("Report");
           this.dispose();
}
     
}
  /*  */

public void cllDialogBox(){

String msg ="<html>Please Test<br>"
        +"<ul>"
        + "<li>Collect blood sample(PBF=peripheral Blood Film Study).</li>"
        + "<li>Bone Marrow Study</li>"
        + "<li>Chest X-RAY</li>"
        + "<li>MRI</li>"
        + "<li>City Scan</li>"
        +"</ul>";
int input = JOptionPane.showOptionDialog(null, msg, "Check Up", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);

if(input == JOptionPane.OK_OPTION)
{
    int cllValue=70;
     ExcelSheet excel = new ExcelSheet(cllValue);
           excel.setVisible(true);
           excel.setTitle("Report");
           this.dispose();
}
}
public void noAction(){

String msg ="<html>Please Test<br>"
        +"<ul>"
        + "<li>Collect blood sample(PBF=peripheral Blood Film Study).</li>"
        + "<li>Bone Marrow Study</li>"
        + "<li>Chest X-RAY</li>"
        + "<li>MRI</li>"
        + "<li>City Scan</li>"
        +"</ul>";
int input = JOptionPane.showOptionDialog(null, msg, "Check Up", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);

if(input == JOptionPane.OK_OPTION)
{
    int noValue=0;
     ExcelSheet excel = new ExcelSheet(noValue);
           excel.setVisible(true);
           excel.setTitle("Report");
           this.dispose();
}
}

}